
package vista.Turno;

import javax.swing.table.DefaultTableModel;
import modelo.GuardarCita;

public class ListadoTurno extends javax.swing.JInternalFrame {
   
    
    
     private DefaultTableModel tableModel = new DefaultTableModel();
    public ListadoTurno(GuardarCita cita) {
        initComponents();
         tbl_listadoTurnos.setModel(tableModel);
        String columnas[] = {"PACIENTE", "FECHA", "HORA", "DOCTOR"};
        tableModel.setColumnIdentifiers(columnas);

        if (cita != null) {
            Object[] fila = {
                cita.getPaciente(),
                cita.getFecha(),
                cita.getHora(),
                cita.getDoctor()
            };
            tableModel.addRow(fila);
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_listadoTurnos = new javax.swing.JTable();

        tbl_listadoTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_listadoTurnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_listadoTurnos;
    // End of variables declaration//GEN-END:variables
}
